### ISSUE TITLE
Definition of submodularity in README.md

### ISSUE THREAD

**Issue by akshayka** [jmschrei/apricot#10]
The definition of submodularity in the README seems to be incorrect. In the readme, it's written 

![image](https://user-images.githubusercontent.com/1994308/77233152-bd975500-6b62-11ea-974b-6abf789dc657.png)

but in the documentation, the inequality sign is reversed

![image](https://user-images.githubusercontent.com/1994308/77233158-ca1bad80-6b62-11ea-936b-4c82026a4639.png)

The latter definition appears to be the correct one.

**Comment by jmschrei** [comment]
Oops you're right. That's what happens when I try to write too quickly.

**Comment by jmschrei** [comment]
Fixed.
