### ISSUE TITLE
Error in running Introduction to Submodular Optimization tutorial: AttributeError: 'FeatureBasedSelection' object has no attribute 'indices'

### ISSUE THREAD

**Issue by DeekshaDixit15** [jmschrei/apricot#11]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-273c285a9f1e> in <module>
      3 selector = FeatureBasedSelection(20)
      4 selector.fit_transform(X_shap)
----> 5 Xi2 = X[selector.indices]
      6 yi2 = y[selector.indices]
      7 

AttributeError: 'FeatureBasedSelection' object has no attribute 'indices'

**Comment by jmschrei** [comment]
Thanks for the report. I think you meant the tutorial "3. Model-Based Selection." I reproduced the error and updated the code cells to use `model.ranking` rather than `model.indices`.

**Comment by DeekshaDixit15** [comment]
Thanks for the update. Yes, I meant Model-Based Selection.
