### ISSUE TITLE
Any reference paper for Graph Cut objective?

### ISSUE THREAD

**Issue by SoumiDas** [jmschrei/apricot#16]
Hi, do we have any paper to refer to for the graph cut objective function? It'll be really helpful to know!

**Comment by jmschrei** [comment]
Howdy. I got it from this paper: https://arxiv.org/pdf/1902.10176.pdf

However, I made a small error in implementation. The issue has been fixed in my latest PR but I haven't yet merged it or released it.

**Comment by SoumiDas** [comment]
Hey thanks! Will wait for the release!

**Comment by jmschrei** [comment]
This should be fixed now.
