### ISSUE TITLE
Retrieving the original index of the samples in subset

### ISSUE THREAD

**Issue by hoangthienan95** [jmschrei/apricot#18]
Hi Jacob,

Thank you for a very cool library. I have a quick question. Maybe I missed something, but right now there are no way to retrieve the original index of the samples in the subset to identify which samples/row number the algorithm chose? This need comes up in 2 scenarios:

1. When I want to know whether I have sufficiently covered my data distribution based on UMAP 2D embedding, I need to know the index of the samples in the subset to merge it back with the UMAP representation

2. When I have features [A, B, C], but only want to perform submodular optimization on features [A, B], and then want to know the values of feature C of all the samples in the subset.

Right now I don't see any way to extract out the index/numpy array row number of the chosen samples.

**Comment by jmschrei** [comment]
Howdy

The `ranking` attribute should return this for you.

**Comment by hoangthienan95** [comment]
Thanks! I felt like I missed something from the docs.
