### ISSUE TITLE
Any plan to implement streaming submodular implementation for the saturated coverage problem?

### ISSUE THREAD

**Issue by badrisnps** [jmschrei/apricot#24]
"Streaming optimization is implemented for mixtures of functions, but not for sum redundancy or saturated coverage functions."

I was wondering if there is a technical reason for the above or just that its doable but not yet implemented. Specifically I was interested in streaming sub-modular optimization for saturated coverage.

**Comment by jmschrei** [comment]
I don't remember there being a reason that it couldn't be implemented. I think that it took longer than expected for me to add in streaming optimization and I needed to move on to the next project after getting a few of the more-common functions working. Unfortunately, I don't currently have plans to expand streaming optimization unless there is huge demand. Sorry. :(

**Comment by badrisnps** [comment]
Thanks! If I find that I need it, perhaps I can review your current implementation for pointers and submit a Pull Request.

**Comment by jmschrei** [comment]
If you happen to implement streaming submodularity for those functions I'd love to review a PR!
