### ISSUE TITLE
bidirectional optimization with Graph Cut ValueError

### ISSUE THREAD

**Issue by M-A-Hassan** [jmschrei/apricot#35]
Thanks for the amazing package and documentation:
I am facing issue when I try to use bidirectional optimization with graph cut
`GraphCutSelection(N_Samples_Per_Class, metric='euclidean', optimizer='bidirectional').fit_transform(..........`
ValueError: zero-size array to reduction operation maximum which has no identity

Note that using other optimizers worked just fine
`GraphCutSelection(N_Samples_Per_Class, metric='euclidean', optimizer='lazy').fit_transform(..........`
`GraphCutSelection(N_Samples_Per_Class, metric='euclidean', optimizer='two-stage').fit_transform(..........`

Your help is appreciated

**Comment by jmschrei** [comment]
Hi @M-A-Hassan. It looks like I never finished the Bidirectional optimizer and I should remove it. Sorry for the inconvenience.

**Comment by M-A-Hassan** [comment]
@jmschrei 
Noted. Thanks
