### ISSUE TITLE
Tag the source

### ISSUE THREAD

**Issue by fabaff** [jmschrei/apricot#38]
Could you please tag the source again? Otherwise all distributions which were shipping this Python module and were using the GitHub releases need to change their description to build the packages.

Thanks

**Comment by jmschrei** [comment]
Sorry, can you elaborate?

**Comment by tschuelia** [comment]
I think what he means is that the Package on pypi is already in version 0.6.1, but the latest Github tag is 0.5.0. So I think it would be good if you could create a new Git Tag and Release for 0.6.1 to match the versions.

**Comment by fabaff** [comment]
The latest release on GitHub is 0.5.0 https://github.com/jmschrei/apricot/releases/tag/v0.5.0. The PyPI release was created  from the [`master`](https://github.com/jmschrei/apricot/blob/master/setup.py#L5) branch.

Tagging would be enough but create a release on GitHub increases the visibility.

**Comment by jmschrei** [comment]
Added

**Comment by fabaff** [comment]
Thank you
