### ISSUE TITLE
Can I use GPU to accelerate the process?

### ISSUE THREAD

**Issue by Adasunnylily** [jmschrei/apricot#41]
I found the process of selecting only use CPU and is very time consuming, I am wondering if there is any way to accelerate or use the GPU for example?
Thanks a lot!

**Comment by Adasunnylily** [comment]
Thanks a lot! I will try later

**Comment by jmschrei** [comment]
To expand on this a little -- many of the algorithms are not easily parallelizable. The greedy algorithm can be orders of magnitude faster than the naive algorithm but involves evaluating an item and then doing logic (putting it back in the queue with a new value, or keeping it). You could evaluate batches of items like this and discard the additional work but it's unclear to me if this would yield much benefit and would be a lot of work to implement correctly.
